[build]
  publish = "dist"
  command = "yarn install; yarn run generate; cp ./env/robots.noprod.txt ./dist/robots.txt"

[context.production]
  command = "yarn install; yarn run generate; cp ./env/robots.prod.txt ./dist/robots.txt"

[[redirects]]
  from = "/submission.html"
  to = "/rules"
  status = 301
